create table tmp_shahar_site_goal_types
(id int(11) primary key auto_increment,
siteid char(32) unique key,
sitename varchar(512),
new_goal_letter char(4),
new_goal_id int(11));

update tmp_shahar_site_goal_types,kmn_sites
set tmp_shahar_site_goal_types.siteid=kmn_sites.siteid
where kmn_sites.sitename=tmp_shahar_site_goal_types.sitename;

select * from tmp_shahar_site_goal_types
where siteid is null;

update tmp_shahar_site_goal_types
set new_goal_id = find_in_set(new_goal_letter,'A,B,C,A+,C+')
where new_goal_letter in ('A','B','C','A+','C+');

select * from tmp_shahar_site_goal_types
where new_goal_letter is null;


create table tmp_shahar_placement_goal_type_change
(id int(11) primary key auto_increment,
`date` date,
layoutid char(32),
optimization_goal_id int(11),
new_goal_id int(11),
key(date,layoutid));

insert into tmp_shahar_placement_goal_type_change (date, layoutid, optimization_goal_id, new_goal_id)
select cast('2016-09-13' as date) `date`, layoutid, l.optimization_goal_id, sst.new_goal_id
from kmn_layouts l
inner join tmp_shahar_site_goal_types sst using(siteid)
inner join (select tagid layoutid from kmn_tag_report r  where r.date >='2016-08-15' and r.impressions>20 group by tagid) a using(layoutid)
where l.optimization_goal_id != sst.new_goal_id
;

select distinct(field)
from kmn_history
where entity_type='placement'
and timestamp>unix_timestamp('2016-07-01'); #'optimization_goal_id'

update kmn_layouts l, tmp_shahar_placement_goal_type_change sgt
set l.optimization_goal_id=sgt.new_goal_id
where sgt.layoutid=l.layoutid
and l.optimization_goal_id != sgt.new_goal_id
and sgt.new_goal_id is not null;

show create table kmn_history;

insert into kmn_history (change_id, entity_type, entity_id, field, new_value, old_value, updated_by, note, timestamp)
select md5(rand()) change_id,'placement' entity_type ,layoutid entity_id,'optimization_goal_id' field, new_goal_id new_value, optimization_goal_id old_value,'shahar@komoona.com' updated_by,'for Yotam' note,1473763938 timestamp
from tmp_shahar_placement_goal_type_change;

select unix_timestamp();


select c.layoutid, l.name, elt(c.optimization_goal_id,'A','B','C','A+','C+') old_goal, elt(c.new_goal_id,'A','B','C','A+','C+') new_goal, sum(r.cost+r.profit) revenue
from tmp_shahar_placement_goal_type_change c
inner join kmn_layouts l using(layoutid)
inner join kmn_tag_report r on r.tagid=c.layoutid
where r.date between '2016-09-05' and '2016-09-11'
group by layoutid
order by revenue desc;

insert into tmp_shahar_site_goal_types (sitename,new_goal_letter)
values 
('Nytimes.com','A+'),
('Boredomtherapy.com','A+'),
('Gatestoneinstitute.org','C+'),
('ShareWareonsale (Sharewareonsale.com)','C+'),
('Braynard.com (spectator.org)','C+'),
('Vacationidea Inc (vacationidea.com)','B'),
('Foodbeast.com','C+'),
('Taunton Press (Finecooking.com)','B'),
('Solspot.com','B'),
('Whatsonnetflix.com','B'),
('Arcamax.com','A'),
('Faithit.com','A'),
('Myjoyonline.com','B'),
('Classmates.com','A+'),
('Mejor Contigo (lamenteesmaravillosa.com)','B'),
('Philly.com','A+'),
('Mugshots.com','C'),
('Traffiq Exchange (uproxx.com)','B'),
('Capitalismisfreedom.com','C'),
('CRTV (conservativereview.com)','B'),
('Gea.de','C+'),
('Yankodesign.com','B'),
('Liberalamerica.org','C'),
('Future Of Capitalism LLC (freebeacon.com)','C+'),
('BlankSlate','B'),
('Clutchfans.net','B'),
('Carambola','C'),
('Pulptastic.com','C+'),
('Petbloglife.com','C'),
('Francium Corp (daystyles.com)','B'),
('Wizzed.com','C+'),
('Mahalo.com','C'),
('Black Box Media dba Local Media Advisor','B'),
('J Carter Marketing (sltrib.com)','B'),
('MapsOfWorld.com','B'),
('Reductress.com','C+'),
('Wetpaint.com','A'),
('Dailysuperheroes.com','B'),
('MediaSource (unforgivengamers.com)','B'),
('D B Corp Ltd. (Bhaskar.com)','C'),
('Get-digital-help.com','B'),
('Calkins','C+'),
('InsideOut Media (iExplore.com)','B'),
('Boardingarea.com','B'),
('Dimplify.com','B'),
('Umbrellas LLC (spikeybits.com)','B'),
('Euclid Media Group (orlandoweekly.com)','C+'),
('Myadstack (mostextremenews.com)','B'),
('Mongabay.com','B'),
('Jpost.com','A'),
('Randaris-anime.net','B'),
('Equinenow.com','B'),
('Bloggersarena.com','C'),
('Mind Tank Media (autooverload.com)','A'),
('GreenSpun Media Group (lasvegassun.com)','C+'),
('Noticierodigital.com','B'),
('Gamerescape.com','B'),
('Tinybeans.com','A'),
('Preventionpulse.com','B'),
('Code9 Media (Worldtimeserver.com)','B'),
('Froppit Inc. (AccessTheStars.com)','B'),
('Lifeluxe.com','B'),
('Diyprojectsforteens.com','C+'),
('Trinidadexpress.com','B'),
('Nowbuzzing.com','B'),
('Singletrackworld.com','B'),
('Businessknowhow.com','B'),
('Goodmenproject.com','B'),
('When-is.com','C+'),
('Zamzar.com','B'),
('Ja606.co.uk','B'),
('Diariodocentrodomundo.com.br','B'),
('PMC (Variety.com)','B'),
('Lifedaily.com','B'),
('Mytrendyhome.com','C+'),
('Suamusica.com.br','A'),
('123 Greetings Inc (123greetings.com)','B'),
('Healthliving.today','B'),
('VerticalScope (guitars101.com)','B'),
('Webspectator (ig.com.br)','A'),
('Movieinsider.com','B'),
('24hourcampfire.com','B'),
('Popcrunch.com','B'),
('Healthyrecipesblogs.com','B'),
('Datpiff.com','B'),
('Stockhouse.com','B'),
('Bikepedia.com','B'),
('Metropoles.com',Null),
('Space Media Network (spacedaily.com)','B'),
('Golsn.com','B'),
('Publir.com','B'),
('Ozar.com','B'),
('Shrug Media (theshrug.net)','A'),
('Uplift Interactive (glamwomen.com)','B'),
('Thejmg.com','B'),
('Nana10.co.il','C'),
('Babypips.com','B'),
('Bright Mountain Media (popularmilitary.com)','B'),
('Viewcelebs.com',Null),
('SparcMedia PTY (nodq.com)','B'),
('Micropulp (thecountrycaller.com)','A'),
('Duffel Media Llc (duffelblog.com)','C+'),
('Socscistatistics.com','B'),
('Kiwilimon.com','B'),
('Happyzebra.com','B'),
('Beepjob (Beepjob.co.uk)','B'),
('Highrated.net','B'),
('WallStCheatSheet.com','B'),
('Travelwednesday.com','B'),
('Webfg (bolsamania.com)','B'),
('Veganricha.com','B'),
('Comicbook.com','B'),
('Fansshare.com','C'),
('Iphonefaq.org','B'),
('UpFizz (Dailyooh.com)','B'),
('Bitbytelife.com','A'),
('Bold.dk','A'),
('Buzzissime.com (dagelijksfun.com)','B'),
('Silenceisconsent.net','B'),
('AdSparc (dailymotion.com)','B'),
('ClearPier (thehollywoodmag.com)','B'),
('Vinted','A'),
('Fathomaway.com','B'),
('Mdjunction.com','B'),
('Experienceproject.com','B'),
('Movieweb.com','B'),
('SharkDog Media (sharktankblog.com)','B'),
('Free-power-point-templates.com','B'),
('24 Minutes (gridread.com)','B'),
('Culture G (senscritique.com)','B'),
('SureSwift Capital Inc. (PythonCentral.io)','B'),
('Justfashiontips.com','B'),
('Sunsigns.org','B'),
('Soledad Media Group (omgwhut.com)','B'),
('Lapatilla.com','B'),
('Caliser.com','B'),
('Peakworthy.com','B'),
('Newormedia (mytechinterviews.com)','C+'),
('Beerock Media (destinylfg.com)','B'),
('Lifepic.me','B'),
('OnVista Media GmbH (onvista.de)','A'),
('Rediff.com','A'),
('Lyricstraining.com','B'),
('Toptales.cc','B'),
('Memegen.com','B'),
('Otakukart.com','B'),
('Otherbuzz.com','A'),
('Timesofisrael.com','A'),
('Capricorn (lemonde.fr)','A'),
('I4U Online GmbH (i4u.com)','B'),
('RTK Media (Buzztache.com)','C+'),
('StreamAMP (Greenatom.net)','B'),
('Higherperspective.com',Null),
('RhythmOne (digitaltrends.com)',Null),
('Webtech media (cvc.com.br)','B'),
('Viralscape.com','B'),
('DDC (newarena.com)','C+'),
('FrontMedia (videnskab.dk)','B'),
('The Eighth, LLC','C+'),
('Tagada Media (peoplefolie.fr)','B'),
('UsedEverywhere.com (Usedvictoria.com)','B'),
('Timetobreak Ltd (gleems.com)','B'),
('Yieldriser (demotywatory.pl)','B'),
('3bluemedia (dailymulligan.com)','B'),
('Messagetoeagle.com','B'),
('GoPoint (Funnelbrain.com)','B'),
('Sodahead.com (huntdrop.com)','B'),
('I Love Coffee',Null),
('WebFox (trend-chaser.com)','B'),
('Fashionback.com','C+'),
('Wazimo (viralmoon.net)','B'),
('Fuel Digital Pte Ltd (covers.com)','B'),
('Forumptd.com','B'),
('Collegeenvy.com','B'),
('Imonomy (foreverceleb.com)','B'),
('ROI Media Consultants (realtor.com)','B'),
('Fenix Media',Null),
('Lifewithtravel.com','C+'),
('Billboard.com','A+'),
('Mindpause.co','B'),
('Hecklerspray.com','B'),
('Buenastareas.com','B'),
('Fangraphs.com','A'),
('Cypok Media (Paroles.net)','B'),
('Leaguecraft.com','B'),
('Besoccer.com','B'),
('Inspirus Media (gamebanshee.com)','B'),
('Modern Web Group (placesyoullsee.com)','C+'),
('Lifed.com','B'),
('Vici Media (patriotjournal.com)','C+'),
('AD Solutions Ltd (pophitz.com)','A'),
('Ingame.de','B'),
('Gossipandgab.com','B'),
('Emptylighthouse.com',Null),
('Gopthedailydose.com',Null),
('Wwfoldschool.com','C+'),
('Phys.org','A'),
('Seriemaniacos.com.br','B'),
('Drafttek.com','B'),
('301 Digital Media (CelebrityTune.com)','B'),
('ViralSmash.org','C+'),
('Internet TV AG (schoener-fernsehen.com)','B'),
('Talkstreamlive.com','B'),
('Bravera Holdings, LLC','B'),
('Core2Digital (tubetamil.com)','B'),
('Express Network Private Limited (newindianexpress.com)','B'),
('Boatos.org','B'),
('Virtualpiano.net','A'),
('Mmorpg.com','B'),
('Us.gratefulgoose.com','B'),
('Olwomen.com','B'),
('Vetti Media (supremepatriot.com)','B'),
('Mundimago.com','B'),
('Mensocietymag.com','C'),
('Noticiasautomotivas.com.br','B'),
('TPN Media Group (thepatriotnation.net)','B'),
('Berlin.de','A+'),
('Sandesh.com','B'),
('Timesofmalta.com',Null),
('Picsofcelebrities.com','B'),
('Convert-me.com','B'),
('Viraloften.com','B'),
('Lycos.com','B'),
('Israelnationalnews.com','B'),
('Designsponge.com','B'),
('Inquisitr.com',Null),
('Korvideo.com','B'),
('Alliance','C'),
('Media Clic (buzzfil.com)','B'),
('BluTonic (dailyvoice.com)','B'),
('Bikerumor.com','B'),
('Bestallergysites.com','A'),
('Hotger Ltd. (Flvto.biz)','C+'),
('Debate.com.mx','B'),
('Pocket-lint (pocket-lint.com)','C+'),
('Transfermarkt GmbH & Co. KG (transfermarkt.it)','A+'),
('Tamilo.com','B'),
('MeteoGroup (wetter24.de)','A'),
('Gta5cheats.com','B'),
('Legendary Speed (legendaryspeed.com)','A'),
('Quizony.com','B'),
('Youtubeinmp3.com','B'),
('Americanmilitarynews.com','B'),
('Allclash.com','B'),
('Gamefools.com','B'),
('TRIBELEADR (positivr.fr)','B'),
('Smash.com','C+'),
('Jones Kilmartin Group (morningticker.com)','B'),
('Generalquizz.com','B'),
('Amazing Media LLC (koobuzz.com)','B'),
('Timvandevall.com','B'),
('Vowgag.com','B'),
('Mylot.com','B'),
('Yaoiotaku.com','B'),
('Leaguelineup.com','B'),
('Worldmapfinder.com','B'),
('Tabforacause.org','B'),
('Dailytwocents.com','B'),
('Viralplots.com',Null),
('Gustakhimaaf.com','B'),
('Adpile (Viraltide.com)','B'),
('Spark Ads Network (Samakal.net)','B'),
('Wildammo.com','A'),
('Haven Marketing (newsobserver.com)','C+'),
('Thecelebritylane.com','B'),
('Mangareader.net',Null),
('Baidu, Inc. (Hao123.com)','A'),
('301 Network (finecooking.com)','B'),
('Lanistaconcepts.com','B'),
('Envero Media (HigherPerspectives.com)','B'),
('Skylikes (buzzit.club)','B'),
('Heymanga.xyz',Null),
('Cringechannel.com','C+'),
('Patriot Ad Network','B'),
('Mangablack.com','C+'),
('Keebali','C'),
('Fashionstyleology.com','A'),
('Chipchick.com','A'),
('Prnt.sc','C+'),
('Mmnews.de','A+'),
('Tumangaonline.com','B'),
('Promt (online-translator.com)','B '),
('Watchcartoononline.com','B'),
('Horriblesubs.info','C'),
('Enigma Media Group, Inc (rocklollipop.com)','B'),
('Stickyday.com','C'),
('Freeroms.com','B'),
('Cartoons8.co','B'),
('Bato.to','A'),
('Nicoblog.org','C+'),
('Ninemanga.com','C+'),
('Mcintosh Marketing (truthandaction.org)','B'),
('SolutionsWide (Viewmixed.com)','B'),
('Navbug.com','B'),
('Sweepsadvantage.com','B'),
('Wishesquotes.com','C+'),
('Nbadraft.net','A'),
('RealNews (trueactivist.com)','B'),
('Mangaeden.com','C+'),
('Mangachapter.me','B'),
('Mangapark.me','B'),
('Newsbarber.com','B'),
('HotPopNow, Inc. (Spikey.com)','C+'),
('Society19.com','A'),
('Sonoma Media Investments (pressdemocrat.com)','A'),
('Healthyandnaturalworld.com','C+'),
('Cybrid Media (johnnyetc.com)','A'),
('Nwzonline.de','B'),
('Rediff.com AU UK CA','A'),
('Mobipicker.com',Null),
('Sohh.com','B'),
('Myfridgefood.com','B'),
('Naruspot.net','C+'),
('Walterfootball.com','C'),
('Dubbedonline.me','C+'),
('Am.com.mx',Null),
('Almasdarnews.com','B'),
('Weberbooks.com',Null),
('Colunadoflamengo.com','B'),
('Brandeating.com','C+'),
('Mundoconsejos.com','C+'),
('Boredbug.com','B'),
('Lankaenews.com','C+'),
('Mydotcomrade.com','B'),
('Watchfomny.com','C+'),
('Popnom.com','B'),
('X17online.com','B'),
('Phoronix.com','B'),
('Theisozone.com','B'),
('PWInsider.com','B'),
('Eliteanimes.com','C+'),
('Skymet Weather Services (skymetweather.com)','C+'),
('Mariasmenu.com',Null),
('Mangasaurus.com','B'),
('1001playlist.com','B'),
('Onlinekhabar.com','C+'),
('Coolrom.com','B'),
('Techeblog.com','B'),
('Lipsum.com','B'),
('The Blogger Network','B'),
('Raise IT Solutions (bdnews24.com)','B'),
('Csgo.steamanalyst.com','B'),
('Vampirefreaks.com','B'),
('Terra Networks Operations Inc (terra.com.br)','A+'),
('Ingenutech, LLC (Bravo.com)','B'),
('Movie-moron.com','B'),
('Sgtreport.com','B'),
('Tuttowrestling.com','B'),
('PressComm Tech (ivg.it)','B'),
('Instantfundas.com','B'),
('Flamingtext.com','B'),
('PrecioLandia.com','B'),
('3dsiso.com','B'),
('Viggle Rewards Inc. (viggle.tv)','B'),
('Whotalking.com','B'),
('Howcast.com','B'),
('Scallywagandvagabond.com','B'),
('Bibliaon.com','B'),
('Mobilism.org','B'),
('Woozworld.com','B'),
('Techverse.net','B'),
('Tweettunnel.com','B'),
('Gotceleb.com','B'),
('Warclans.com','B'),
('Jigsawplanet.com','B'),
('Profootballspot.com','B'),
('Onedio (onedio.com)','B'),
('Booshsports.com','B'),
('GTANet','B'),
('Conva Media (trend-guru.com)','B'),
('Adotize (prowrestling.com)','B'),
('Bitlanders.com','B'),
('Master Games International (Tentonhammer.com)','B'),
('Conversationexchange.com','B'),
('Terezowens.com','B'),
('Dbstalk.com','B'),
('Aggiustatutto.it','B'),
('Twitrcovers.com','B'),
('Firstcovers.com','B'),
('Dalealplay.es','B'),
('ADAPT Network (Adaptnetwork.com)','B'),
('Browsi (90min.com)',Null),
('Qineqt Health Inc (TechNewsToday.com)','B'),
('Zgrg (ocubee.com)',Null),
('Ibancalculator.com','B'),
('FourScoreDigital (grabien.com)','B'),
('Ranker.com','A'),
('Steephill.tv','B'),
('Rotter.net','B'),
('Justtamilsongs.com',Null),
('Snazzyspace.com','B'),
('Imaging-resource.com','B'),
('Animecenter.tv',Null),
('Monitor.hr','B'),
('Cooltechlists.com','B'),
('Witalks.com',Null),
('Andhraguide.com','B'),
('GNT Media (compartir-tecnologias.es)','B'),
('Lazyslack.com','B'),
('Madvertise Media (celepedia.de)','A'),
('Addoox (tudogostoso.com.br)','B'),
('Sibannac Media (lifeisaboard.com)','B'),
('Theroastroom.com',Null),
('Guru Media International (Veryviral.com)','B'),
('3dgames.com.ar','B'),
('Documaniatv.com','B'),
('Maven Media Group ltd. (Boattrader.com)','B'),
('Wired Media (Gymplan.com)','C+'),
('Eliteprospects.com','A'),
('Crowdgather.com','C+'),
('Berez Media, LLC (Onlinechic.com)','B'),
('Mundopositivo.com.br','A'),
('Allpar.com','B'),
('Fullmatchesandshows.com','B'),
('Tri Media (Tattoo.com)','B'),
('Boredfails.com','C+'),
('Bright Line Media','B'),
('Income Store (Homeremedyshop.com)','B'),
('Argo Blue (weget.mobi)','B'),
('Glossyfeed.com','C+'),
('Telechargerunevideo.com','C+'),
('Encyclopediadramatica.se',Null),
('Beforeitsnews.com','B'),
('Dailyspikes.com','C'),
('Tubereplay.com','B'),
('Keepinspiring.me','B'),
('Thedailyengage.com','B'),
('Minitokyo.net','B'),
('Sanfoundry.com','B'),
('NetAvenir (Iconosquare.com)','B'),
('Scan-manga.com','B'),
('Stardom Labs (animalpolitico.com)','B'),
('Musicmundial.com',Null),
('Bocalista.com','B'),
('A2zWordFinder.com','B'),
('Minilua.com',Null),
('Citador.pt',Null),
('Peekworthy.com','B'),
('Aujourdhui.com','B'),
('Hawtcelebs.com','B'),
('Dasort.com','B'),
('Unixmanga.net','B'),
('Mangahop.com','C+'),
('Dicelacancion.com','B'),
('Sem Seo y Mas (somosinvictos.com)','B'),
('Unmotivating.com','B'),
('Themindcircle.com','B'),
('HAVA Holding AS (bulbapedia.bulbagarden.net)',Null),
('Ccma.cat','B'),
('Japscan.com','B'),
('Pleroma Media (techtimes.com)',Null),
('Emuparadise.me','A+'),
('Digital Door Media','B'),
('Osoted.com','B'),
('Returnofkings.com',Null),
('C⌠ng ty C? ph?n BG24 (all4share.net)',Null),
('Justgirlythings.co','B'),
('Asiantown.net','B'),
('Sathyamonline.com','B'),
('Mansueto.com (inc.com)',Null),
('Rawstory.com','B'),
('Trinilulz.com','B'),
('NGames',Null),
('ThingsRated.com','B'),
('Barons Media (Hypster.com)','B'),
('Izaz.eu','B'),
('Getcomics.info',Null);

